
[38;5;228;48;5;63;1m apt.source [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                   [0m
[0m[38;5;252m                                                                                [0m
[38;5;252mAdd apt source repository(ies), and update the available packages list if needed[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                               [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                   [0m
[0m[38;5;252m                                                                                [0m
[38;5;252m• Local name of the source(s) (simple short text)                               [0m
[38;5;252m• Source(s)                                                                     [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                               [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                     [0m
[0m[38;5;252m                                                                                [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mNextDNS[38;5;252m [0m[38;5;252m                                                                      [0m
[0m[38;5;252m  [0m[38;5;251m  apt.source nextdns "deb https://repo.nextdns.io/deb stable main"[38;5;252m [0m[38;5;252m           [0m
[0m
