
[38;5;228;48;5;63;1m apt.source [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                   [0m
[0m[38;5;234m                                                                                [0m
[38;5;234mAdd apt source repository(ies), and update the available packages list if needed[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                               [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                   [0m
[0m[38;5;234m                                                                                [0m
[38;5;234m• Local name of the source(s) (simple short text)                               [0m
[38;5;234m• Source(s)                                                                     [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                               [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                     [0m
[0m[38;5;234m                                                                                [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mNextDNS[38;5;234m [0m[38;5;234m                                                                      [0m
[0m[38;5;234m  [0m[38;5;235m  apt.source nextdns "deb https://repo.nextdns.io/deb stable main"[38;5;234m [0m[38;5;234m           [0m
[0m
