
[38;5;228;48;5;63;1m dpkg.install [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                    [0m
[0m[38;5;234m                                                                   [0m
[38;5;234mInstall a package using dpkg (does not check the file exists first)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                  [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                      [0m
[0m[38;5;234m                                                                   [0m
[38;5;234m• Absolute path to the package file                                [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                  [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                        [0m
[0m[38;5;234m                                                                   [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mInstall that awesome package[38;5;234m [0m[38;5;234m                                    [0m
[0m[38;5;234m  [0m[38;5;235m  dpkg.install <confdir>/my-awesome-stuff.deb[38;5;234m [0m[38;5;234m                   [0m
[0m
