
[38;5;228;48;5;63;1m file.absent [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                          [0m
[0m[38;5;234m                                                                        [0m
[38;5;234mMake sure a file is absent                                              [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                       [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                           [0m
[0m[38;5;234m                                                                        [0m
[38;5;234m• Absolute path of the file to remove (including directory with content)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                       [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                             [0m
[0m[38;5;234m                                                                        [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mMake sure there is no "Photos" directory for jack[38;5;234m [0m[38;5;234m                    [0m
[0m[38;5;234m  [0m[38;5;235m  file.absent /home/jack/Photos[38;5;234m [0m[38;5;234m                                      [0m
[0m
