
[38;5;228;48;5;63;1m file.absent [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                          [0m
[0m[38;5;252m                                                                        [0m
[38;5;252mMake sure a file is absent                                              [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                       [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                           [0m
[0m[38;5;252m                                                                        [0m
[38;5;252m• Absolute path of the file to remove (including directory with content)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                       [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                             [0m
[0m[38;5;252m                                                                        [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mMake sure there is no "Photos" directory for jack[38;5;252m [0m[38;5;252m                    [0m
[0m[38;5;252m  [0m[38;5;251m  file.absent /home/jack/Photos[38;5;252m [0m[38;5;252m                                      [0m
[0m
