
[38;5;228;48;5;63;1m flatpak.install [0m[38;5;252m[38;5;252m [0m[38;5;252m                        [0m
[0m[38;5;252m                                          [0m
[38;5;252mInstall a package using flatpak           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                         [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                             [0m
[0m[38;5;252m                                          [0m
[38;5;252m• Application ID of the package to install[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                         [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                               [0m
[0m[38;5;252m                                          [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mInstall "anydesk"[38;5;252m [0m[38;5;252m                      [0m
[0m[38;5;252m  [0m[38;5;251m  flatpak.install com.anydesk.Anydesk[38;5;252m [0m[38;5;252m  [0m
[0m
