
[38;5;228;48;5;63;1m flatpak.install [0m[38;5;234m[38;5;234m [0m[38;5;234m                        [0m
[0m[38;5;234m                                          [0m
[38;5;234mInstall a package using flatpak           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                         [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                             [0m
[0m[38;5;234m                                          [0m
[38;5;234m• Application ID of the package to install[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                         [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                               [0m
[0m[38;5;234m                                          [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mInstall "anydesk"[38;5;234m [0m[38;5;234m                      [0m
[0m[38;5;234m  [0m[38;5;235m  flatpak.install com.anydesk.Anydesk[38;5;234m [0m[38;5;234m  [0m
[0m
