
[38;5;228;48;5;63;1m git.hash [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                      [0m
[0m[38;5;234m                                                                                 [0m
[38;5;234mGet the latest hash for a reference (generally branch or tag) in a git repository[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                    [0m
[0m[38;5;234m                                                                                 [0m
[38;5;234m• Git repository URI                                                             [0m
[38;5;234m• Reference (generally, branch or tag)                                           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                [0m
[0m[38;5;27;1m## Outputs[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                      [0m
[0m[38;5;234m                                                                                 [0m
[38;5;234m• Commit hash                                                                    [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                      [0m
[0m[38;5;234m                                                                                 [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mPop Shell[38;5;234m [0m[38;5;234m                                                                     [0m
[0m[38;5;234m  [0m[38;5;235m  pophash = git.hash https://github.com/pop-os/shell.git master[38;5;234m [0m[38;5;234m               [0m
[0m
