
[38;5;228;48;5;63;1m github.latest.stable [0m[38;5;252m[38;5;252m [0m[38;5;252m                                          [0m
[0m[38;5;252m                                                                 [0m
[38;5;252mCheck the latest stable release from a GitHub repository         [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                    [0m
[0m[38;5;252m                                                                 [0m
[38;5;252m• GitHub repository name                                         [0m
[38;5;252m• Pattern to match an asset                                      [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                [0m
[0m[38;5;39;1m## Outputs[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                      [0m
[0m[38;5;252m                                                                 [0m
[38;5;252m• Release name                                                   [0m
[38;5;252m• Asset URL                                                      [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                      [0m
[0m[38;5;252m                                                                 [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mKmonad[38;5;252m [0m[38;5;252m                                                        [0m
[0m[38;5;252m  [0m[38;5;251m  release url = github.latest.stable kmonad/kmonad kmonad-*-linux[0m
[0m
