
[38;5;228;48;5;63;1m gnome.extension.install [0m[38;5;234m[38;5;234m [0m[38;5;234m                               [0m
[0m[38;5;234m                                                         [0m
[38;5;234mInstall a GNOME Shell extension from extensions.gnome.org[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                        [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                            [0m
[0m[38;5;234m                                                         [0m
[38;5;234m• Extension UUID                                         [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                        [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                              [0m
[0m[38;5;234m                                                         [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mDash to dock[38;5;234m [0m[38;5;234m                                          [0m
[0m[38;5;234m  [0m[38;5;235m  gnome.extension.install dash-to-dock@micxgx.gmail.com[0m
[0m[38;5;234m  [0m[38;5;235m  gnome.extension.enable dash-to-dock@micxgx.gmail.com[38;5;234m [0m
[0m
