
[38;5;228;48;5;63;1m http.get.file [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                         [0m
[0m[38;5;252m                                                                         [0m
[38;5;252mDownload a file with a HTTP GET request (URI is downloaded when applying)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                        [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                            [0m
[0m[38;5;252m                                                                         [0m
[38;5;252m• URI of the file to download                                            [0m
[38;5;252m• Path of the destination file                                           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                        [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                              [0m
[0m[38;5;252m                                                                         [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mDownload example[38;5;252m [0m[38;5;252m                                                      [0m
[0m[38;5;252m  [0m[38;5;251m  http.get.file http://www.example.com /opt/example[38;5;252m [0m[38;5;252m                   [0m
[0m
