
[38;5;228;48;5;63;1m http.get.file [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                         [0m
[0m[38;5;234m                                                                         [0m
[38;5;234mDownload a file with a HTTP GET request (URI is downloaded when applying)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                        [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                            [0m
[0m[38;5;234m                                                                         [0m
[38;5;234m• URI of the file to download                                            [0m
[38;5;234m• Path of the destination file                                           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                        [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                              [0m
[0m[38;5;234m                                                                         [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mDownload example[38;5;234m [0m[38;5;234m                                                      [0m
[0m[38;5;234m  [0m[38;5;235m  http.get.file http://www.example.com /opt/example[38;5;234m [0m[38;5;234m                   [0m
[0m
