
[38;5;228;48;5;63;1m http.post.var [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                  [0m
[0m[38;5;234m                                                                  [0m
[38;5;234mSend content with a HTTP POST request (data is sent when checking)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                 [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                     [0m
[0m[38;5;234m                                                                  [0m
[38;5;234m• URI of the content to download                                  [0m
[38;5;234m• Body (payload)                                                  [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                 [0m
[0m[38;5;27;1m## Outputs[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                       [0m
[0m[38;5;234m                                                                  [0m
[38;5;234m• Downloaded content                                              [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                 [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                       [0m
[0m[38;5;234m                                                                  [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mDownload example[38;5;234m [0m[38;5;234m                                               [0m
[0m[38;5;234m  [0m[38;5;235m  foobar = http.post.var http://www.example.com "example data"[38;5;234m [0m[38;5;234m [0m
[0m
