
[38;5;228;48;5;63;1m http.post.var [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                  [0m
[0m[38;5;252m                                                                  [0m
[38;5;252mSend content with a HTTP POST request (data is sent when checking)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                 [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                     [0m
[0m[38;5;252m                                                                  [0m
[38;5;252m• URI of the content to download                                  [0m
[38;5;252m• Body (payload)                                                  [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                 [0m
[0m[38;5;39;1m## Outputs[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                       [0m
[0m[38;5;252m                                                                  [0m
[38;5;252m• Downloaded content                                              [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                 [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                       [0m
[0m[38;5;252m                                                                  [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mDownload example[38;5;252m [0m[38;5;252m                                               [0m
[0m[38;5;252m  [0m[38;5;251m  foobar = http.post.var http://www.example.com "example data"[38;5;252m [0m[38;5;252m [0m
[0m
