
[38;5;228;48;5;63;1m nm.hotspot [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                  [0m
[0m[38;5;234m                                                                               [0m
[38;5;234mSetup a wifi access point (hotspot) - only one can be configured               [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                              [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                  [0m
[0m[38;5;234m                                                                               [0m
[38;5;234m• Network Interface name                                                       [0m
[38;5;234m• SSID of the hotspot                                                          [0m
[38;5;234m• PSK of the hotspot (password)                                                [0m
[38;5;234m• Autoconnect (one of: 1, t, T, TRUE, true, True, 0, f, F, FALSE, false, False)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                              [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                    [0m
[0m[38;5;234m                                                                               [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mShare connection[38;5;234m [0m[38;5;234m                                                            [0m
[0m[38;5;234m  [0m[38;5;235m  nm.hotspot wlp4s0 mynetwork n0tSecureP4ssw0rd true[38;5;234m [0m[38;5;234m                        [0m
[0m
