
[38;5;228;48;5;63;1m nm.import [0m[38;5;234m[38;5;234m [0m[38;5;234m                                [0m
[0m[38;5;234m                                            [0m
[38;5;234mImport a VPN configuration in NetworkManager[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                           [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                               [0m
[0m[38;5;234m                                            [0m
[38;5;234m• Type of the VPN                           [0m
[38;5;234m• Path of the configuration file to import  [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                           [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                 [0m
[0m[38;5;234m                                            [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mImport my VPN configuration[38;5;234m [0m[38;5;234m              [0m
[0m[38;5;234m  [0m[38;5;235m  nm.import openvpn /opt/openvpn.conf[38;5;234m [0m[38;5;234m    [0m
[0m
