
[38;5;228;48;5;63;1m snap.install [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                               [0m
[0m[38;5;252m                                                                                              [0m
[38;5;252mInstall a package using snap                                                                  [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                             [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                 [0m
[0m[38;5;252m                                                                                              [0m
[38;5;252m• Name of the package to install                                                              [0m
[38;5;252m• Options, comma-separated, at least one of: stable, candidate, edge, beta, classic, dangerous[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                             [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                   [0m
[0m[38;5;252m                                                                                              [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mInstall node[38;5;252m [0m[38;5;252m                                                                               [0m
[0m[38;5;252m  [0m[38;5;251m  snap.install node stable[38;5;252m [0m[38;5;252m                                                                 [0m
[0m
