
[38;5;228;48;5;63;1m snap.install [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                               [0m
[0m[38;5;234m                                                                                              [0m
[38;5;234mInstall a package using snap                                                                  [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                             [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                 [0m
[0m[38;5;234m                                                                                              [0m
[38;5;234m• Name of the package to install                                                              [0m
[38;5;234m• Options, comma-separated, at least one of: stable, candidate, edge, beta, classic, dangerous[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                             [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                   [0m
[0m[38;5;234m                                                                                              [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mInstall node[38;5;234m [0m[38;5;234m                                                                               [0m
[0m[38;5;234m  [0m[38;5;235m  snap.install node stable[38;5;234m [0m[38;5;234m                                                                 [0m
[0m
