
[38;5;228;48;5;63;1m stack.install [0m[38;5;252m[38;5;252m [0m[38;5;252m                        [0m
[0m[38;5;252m                                        [0m
[38;5;252mExecute the stack command (from Haskell)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                       [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                           [0m
[0m[38;5;252m                                        [0m
[38;5;252m• Directory where to execute the command[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                       [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                             [0m
[0m[38;5;252m                                        [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mInstall foobar[38;5;252m [0m[38;5;252m                       [0m
[0m[38;5;252m  [0m[38;5;251m  stack.install /tmp/foobar[38;5;252m [0m[38;5;252m          [0m
[0m
