
[38;5;228;48;5;63;1m stack.install [0m[38;5;234m[38;5;234m [0m[38;5;234m                        [0m
[0m[38;5;234m                                        [0m
[38;5;234mExecute the stack command (from Haskell)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                       [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                           [0m
[0m[38;5;234m                                        [0m
[38;5;234m• Directory where to execute the command[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                       [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                             [0m
[0m[38;5;234m                                        [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mInstall foobar[38;5;234m [0m[38;5;234m                       [0m
[0m[38;5;234m  [0m[38;5;235m  stack.install /tmp/foobar[38;5;234m [0m[38;5;234m          [0m
[0m
