
[38;5;228;48;5;63;1m tempdir [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                    [0m
[0m[38;5;252m                                                                                              [0m
[38;5;252mCreate a temporary directory (directory is automatically deleted when closing the application)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                             [0m
[0m[38;5;39;1m## Outputs[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                   [0m
[0m[38;5;252m                                                                                              [0m
[38;5;252m• Path of the created directory                                                               [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                             [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                   [0m
[0m[38;5;252m                                                                                              [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mTemporarily clone git repository[38;5;252m [0m[38;5;252m                                                           [0m
[0m[38;5;252m  [0m[38;5;251m  tmp = tempdir[38;5;252m [0m[38;5;252m                                                                            [0m
[0m[38;5;252m  [0m[38;5;251m  git.clone https://www.example.com/foobar.git <tmp>[38;5;252m [0m[38;5;252m                                       [0m
[0m
