
[38;5;228;48;5;63;1m user.systemd.enable [0m[38;5;234m[38;5;234m [0m[38;5;234m                 [0m
[0m[38;5;234m                                       [0m
[38;5;234mEnable and start a systemd user service[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                      [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                          [0m
[0m[38;5;234m                                       [0m
[38;5;234m• Username                             [0m
[38;5;234m• Name of the service to enable        [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                      [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                            [0m
[0m[38;5;234m                                       [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mEnable syncthing[38;5;234m [0m[38;5;234m                    [0m
[0m[38;5;234m  [0m[38;5;235m  systemd.enable alice syncthing[38;5;234m [0m[38;5;234m    [0m
[0m
