
[38;5;228;48;5;63;1m user.group [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                         [0m
[0m[38;5;234m                                                                      [0m
[38;5;234mAdd the user to the group (if the group does not exist, it is created)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                     [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                         [0m
[0m[38;5;234m                                                                      [0m
[38;5;234m• Username                                                            [0m
[38;5;234m• Groupname                                                           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                     [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                           [0m
[0m[38;5;234m                                                                      [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mAllow alice to dial with a modem[38;5;234m [0m[38;5;234m                                   [0m
[0m[38;5;234m  [0m[38;5;235m  user.group alice dialout[38;5;234m [0m[38;5;234m                                         [0m
[0m
