
[38;5;228;48;5;63;1m user.git.config [0m[38;5;252m[38;5;252m [0m[38;5;252m                                   [0m
[0m[38;5;252m                                                     [0m
[38;5;252mSet a git configuration parameter for a user         [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                    [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                        [0m
[0m[38;5;252m                                                     [0m
[38;5;252m• Username                                           [0m
[38;5;252m• Name (in the form "x.y")                           [0m
[38;5;252m• Value                                              [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                    [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                          [0m
[0m[38;5;252m                                                     [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mGit parameter[38;5;252m [0m[38;5;252m                                     [0m
[0m[38;5;252m  [0m[38;5;251m  user.git.config alice branch.autosetuprebase[38;5;252m [0m[38;5;252m    [0m
[0m[38;5;251malways[38;5;252m [0m[38;5;252m                                              [0m
[0m
