
[38;5;228;48;5;63;1m user.dconf.set [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                 [0m
[0m[38;5;252m                                                                  [0m
[38;5;252mSet a dconf parameter                                             [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                 [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                     [0m
[0m[38;5;252m                                                                  [0m
[38;5;252m• Username                                                        [0m
[38;5;252m• Key (in the form "/x/y/z")                                      [0m
[38;5;252m• Value                                                           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                 [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                       [0m
[0m[38;5;252m                                                                  [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mShow date in GNOME[38;5;252m [0m[38;5;252m                                             [0m
[0m[38;5;252m  [0m[38;5;251m  user.dconf.set /org/gnome/desktop/interface/clock-show-date true[0m
[0m
