
[38;5;228;48;5;63;1m user.group [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                         [0m
[0m[38;5;252m                                                                      [0m
[38;5;252mAdd the user to the group (if the group does not exist, it is created)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                     [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                         [0m
[0m[38;5;252m                                                                      [0m
[38;5;252m• Username                                                            [0m
[38;5;252m• Groupname                                                           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                     [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                           [0m
[0m[38;5;252m                                                                      [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mAllow alice to dial with a modem[38;5;252m [0m[38;5;252m                                   [0m
[0m[38;5;252m  [0m[38;5;251m  user.group alice dialout[38;5;252m [0m[38;5;252m                                         [0m
[0m
