
[38;5;228;48;5;63;1m user.git.config [0m[38;5;234m[38;5;234m [0m[38;5;234m                                   [0m
[0m[38;5;234m                                                     [0m
[38;5;234mSet a git configuration parameter for a user         [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                    [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                        [0m
[0m[38;5;234m                                                     [0m
[38;5;234m• Username                                           [0m
[38;5;234m• Name (in the form "x.y")                           [0m
[38;5;234m• Value                                              [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                    [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                          [0m
[0m[38;5;234m                                                     [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mGit parameter[38;5;234m [0m[38;5;234m                                     [0m
[0m[38;5;234m  [0m[38;5;235m  user.git.config alice branch.autosetuprebase[38;5;234m [0m[38;5;234m    [0m
[0m[38;5;235malways[38;5;234m [0m[38;5;234m                                              [0m
[0m
