
[38;5;228;48;5;63;1m user.git.clone [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                              [0m
[0m[38;5;234m                                                                                                                                                               [0m
[38;5;234mClone a git repository as provided user (if the repository already exists locally, pull the last commit) and switch to the requested reference (branch, tag...)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                              [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                  [0m
[0m[38;5;234m                                                                                                                                                               [0m
[38;5;234m• Username                                                                                                                                                     [0m
[38;5;234m• Remote repository URI                                                                                                                                        [0m
[38;5;234m• Clone target (if path is relative, it is relative to the user's nome directory)                                                                              [0m
[38;5;234m• Reference (branch, tag...)                                                                                                                                   [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                              [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                    [0m
[0m[38;5;234m                                                                                                                                                               [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mOh My Bash[38;5;234m [0m[38;5;234m                                                                                                                                                  [0m
[0m[38;5;234m  [0m[38;5;235m  user.git.clone alice https://github.com/ohmybash/oh-my-bash.git .oh-my-bash master[38;5;234m [0m[38;5;234m                                                                        [0m
[0m
