
[38;5;228;48;5;63;1m user.xdg.userdir [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                      [0m
[0m[38;5;252m                                                                                                                         [0m
[38;5;252mSet a XDG user dir                                                                                                       [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                        [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                            [0m
[0m[38;5;252m                                                                                                                         [0m
[38;5;252m• Username                                                                                                               [0m
[38;5;252m• Directory name (one of DESKTOP, DOWNLOAD, TEMPLATES, PUBLICSHARE, DOCUMENTS, MUSIC, PICTURES, VIDEOS, case-insensitive)[0m
[38;5;252m• Directory path                                                                                                         [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                        [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                              [0m
[0m[38;5;252m                                                                                                                         [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mChange downloads directory for john[38;5;252m [0m[38;5;252m                                                                                   [0m
[0m[38;5;252m  [0m[38;5;251m  user.file.directory john Downs[38;5;252m [0m[38;5;252m                                                                                      [0m
[0m[38;5;252m  [0m[38;5;251m  user.xdg.userdir john DOWNLOAD Downs[38;5;252m [0m[38;5;252m                                                                                [0m
[0m
