
[38;5;228;48;5;63;1m user.gnome.extension.enable [0m[38;5;252m[38;5;252m [0m[38;5;252m                                   [0m
[0m[38;5;252m                                                                 [0m
[38;5;252mEnable a GNOME Shell extension                                   [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                    [0m
[0m[38;5;252m                                                                 [0m
[38;5;252m• Username                                                       [0m
[38;5;252m• UUID of the extension                                          [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                      [0m
[0m[38;5;252m                                                                 [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mDash to dock[38;5;252m [0m[38;5;252m                                                  [0m
[0m[38;5;252m  [0m[38;5;251m  gnome.extension.install dash-to-dock@micxgx.gmail.com[38;5;252m [0m[38;5;252m       [0m
[0m[38;5;252m  [0m[38;5;251m  user.gnome.extension.enable alice dash-to-dock@micxgx.gmail.com[0m
[0m
