
[38;5;228;48;5;63;1m user.go.env [0m[38;5;234m[38;5;234m [0m[38;5;234m                                      [0m
[0m[38;5;234m                                                    [0m
[38;5;234mSet a Go environment variable                       [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                   [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                       [0m
[0m[38;5;234m                                                    [0m
[38;5;234m• Username                                          [0m
[38;5;234m• Variable name (automatically changed to uppercase)[0m
[38;5;234m• Value                                             [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                   [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                         [0m
[0m[38;5;234m                                                    [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mGo path[38;5;234m [0m[38;5;234m                                          [0m
[0m[38;5;234m  [0m[38;5;235m  user.go.env alice gopath /home/alice/GO[38;5;234m [0m[38;5;234m        [0m
[0m
