
[38;5;228;48;5;63;1m user.vscode.extension.install [0m[38;5;234m[38;5;234m [0m[38;5;234m               [0m
[0m[38;5;234m                                               [0m
[38;5;234mInstall a VSCode extension                     [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                              [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                  [0m
[0m[38;5;234m                                               [0m
[38;5;234m• Username                                     [0m
[38;5;234m• Extension identifier                         [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                              [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                    [0m
[0m[38;5;234m                                               [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mVSCode with go[38;5;234m [0m[38;5;234m                              [0m
[0m[38;5;234m  [0m[38;5;235m  snap.install code classic[38;5;234m [0m[38;5;234m                 [0m
[0m[38;5;234m  [0m[38;5;235m  user.vscode.extension.install alice[38;5;234m [0m[38;5;234m       [0m
[0m[38;5;235mgolang.go[38;5;234m [0m[38;5;234m                                     [0m
[0m
