
[38;5;228;48;5;63;1m user.file.directory [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                          [0m
[0m[38;5;234m                                                                                                                [0m
[38;5;234mCreate a directory belonging to the given user (if path is relative, it is relative to the user's home directory[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                               [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                   [0m
[0m[38;5;234m                                                                                                                [0m
[38;5;234m• Username                                                                                                      [0m
[38;5;234m• Directory path                                                                                                [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                               [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                     [0m
[0m[38;5;234m                                                                                                                [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mCreate Picz photos for alice[38;5;234m [0m[38;5;234m                                                                                 [0m
[0m[38;5;234m  [0m[38;5;235m  user.file.directory alice Picz[38;5;234m [0m[38;5;234m                                                                             [0m
[0m
