
[38;5;228;48;5;63;1m user.go.env [0m[38;5;252m[38;5;252m [0m[38;5;252m                                      [0m
[0m[38;5;252m                                                    [0m
[38;5;252mSet a Go environment variable                       [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                   [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                       [0m
[0m[38;5;252m                                                    [0m
[38;5;252m• Username                                          [0m
[38;5;252m• Variable name (automatically changed to uppercase)[0m
[38;5;252m• Value                                             [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                   [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                         [0m
[0m[38;5;252m                                                    [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mGo path[38;5;252m [0m[38;5;252m                                          [0m
[0m[38;5;252m  [0m[38;5;251m  user.go.env alice gopath /home/alice/GO[38;5;252m [0m[38;5;252m        [0m
[0m
