
[38;5;228;48;5;63;1m user.gnome.extension.enable [0m[38;5;234m[38;5;234m [0m[38;5;234m                                   [0m
[0m[38;5;234m                                                                 [0m
[38;5;234mEnable a GNOME Shell extension                                   [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                    [0m
[0m[38;5;234m                                                                 [0m
[38;5;234m• Username                                                       [0m
[38;5;234m• UUID of the extension                                          [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                      [0m
[0m[38;5;234m                                                                 [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mDash to dock[38;5;234m [0m[38;5;234m                                                  [0m
[0m[38;5;234m  [0m[38;5;235m  gnome.extension.install dash-to-dock@micxgx.gmail.com[38;5;234m [0m[38;5;234m       [0m
[0m[38;5;234m  [0m[38;5;235m  user.gnome.extension.enable alice dash-to-dock@micxgx.gmail.com[0m
[0m
