
[38;5;228;48;5;63;1m user.dconf.set [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                 [0m
[0m[38;5;234m                                                                  [0m
[38;5;234mSet a dconf parameter                                             [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                 [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                     [0m
[0m[38;5;234m                                                                  [0m
[38;5;234m• Username                                                        [0m
[38;5;234m• Key (in the form "/x/y/z")                                      [0m
[38;5;234m• Value                                                           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                 [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                       [0m
[0m[38;5;234m                                                                  [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mShow date in GNOME[38;5;234m [0m[38;5;234m                                             [0m
[0m[38;5;234m  [0m[38;5;235m  user.dconf.set /org/gnome/desktop/interface/clock-show-date true[0m
[0m
