
[38;5;228;48;5;63;1m xdg.mimedefault [0m[38;5;252m[38;5;252m [0m[38;5;252m                           [0m
[0m[38;5;252m                                             [0m
[38;5;252mSet the default application for a mimetype   [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                            [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                [0m
[0m[38;5;252m                                             [0m
[38;5;252m• Mimetype                                   [0m
[38;5;252m• Name of the application                    [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                            [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                  [0m
[0m[38;5;252m                                             [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mUse Chromium[38;5;252m [0m[38;5;252m                              [0m
[0m[38;5;252m  [0m[38;5;251m  xdg.mimedefault text/html[38;5;252m [0m[38;5;252m               [0m
[0m[38;5;251mchromium_chromium[38;5;252m [0m[38;5;252m                           [0m
[0m
