
[38;5;228;48;5;63;1m dpkg.install [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                    [0m
[0m[38;5;252m                                                                   [0m
[38;5;252mInstall a package using dpkg (does not check the file exists first)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                  [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                      [0m
[0m[38;5;252m                                                                   [0m
[38;5;252m• Absolute path to the package file                                [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                  [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                        [0m
[0m[38;5;252m                                                                   [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mInstall that awesome package[38;5;252m [0m[38;5;252m                                    [0m
[0m[38;5;252m  [0m[38;5;251m  dpkg.install <confdir>/my-awesome-stuff.deb[38;5;252m [0m[38;5;252m                   [0m
[0m
