
[38;5;228;48;5;63;1m file.move.nocheck [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                [0m
[0m[38;5;234m                                                                                                                                                                    [0m
[38;5;234mMove a file or directory to another place (with no check). Necessary if the file does not exist in the check phase (for instance if it is downloaded when applying).[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                                   [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                       [0m
[0m[38;5;234m                                                                                                                                                                    [0m
[38;5;234m• Souce path                                                                                                                                                        [0m
[38;5;234m• Destination path                                                                                                                                                  [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                                   [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                                         [0m
[0m[38;5;234m                                                                                                                                                                    [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mMove previous documents directory for jane[38;5;234m [0m[38;5;234m                                                                                                                       [0m
[0m[38;5;234m  [0m[38;5;235m  file.move.nocheck /home/jane.old/Documents /home/jane/Documents[38;5;234m [0m[38;5;234m                                                                                                [0m
[0m
