
[38;5;228;48;5;63;1m file.extract [0m[38;5;234m[38;5;234m [0m[38;5;234m                      [0m
[0m[38;5;234m                                     [0m
[38;5;234mExtract a (compressed) archive       [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                    [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                        [0m
[0m[38;5;234m                                     [0m
[38;5;234m• Archive format (one of zip, tar.xz)[0m
[38;5;234m• Archive absolute path              [0m
[38;5;234m• Target absolute path               [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                    [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                          [0m
[0m[38;5;234m                                     [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mExtract something[38;5;234m [0m[38;5;234m                 [0m
[0m[38;5;234m  [0m[38;5;235m  file.extract zip /foo/bar.zip[38;5;234m [0m[38;5;234m   [0m
[0m[38;5;235m/bar[38;5;234m [0m[38;5;234m                                [0m
[0m
