
[38;5;228;48;5;63;1m file.extract [0m[38;5;252m[38;5;252m [0m[38;5;252m                      [0m
[0m[38;5;252m                                     [0m
[38;5;252mExtract a (compressed) archive       [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                    [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                        [0m
[0m[38;5;252m                                     [0m
[38;5;252m• Archive format (one of zip, tar.xz)[0m
[38;5;252m• Archive absolute path              [0m
[38;5;252m• Target absolute path               [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                    [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                          [0m
[0m[38;5;252m                                     [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mExtract something[38;5;252m [0m[38;5;252m                 [0m
[0m[38;5;252m  [0m[38;5;251m  file.extract zip /foo/bar.zip[38;5;252m [0m[38;5;252m   [0m
[0m[38;5;251m/bar[38;5;252m [0m[38;5;252m                                [0m
[0m
