
[38;5;228;48;5;63;1m git.clone [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                  [0m
[0m[38;5;234m                                                                                                                                              [0m
[38;5;234mClone a git repository (if the repository already exists locally, pull the last commit) and switch to the requested reference (branch, tag...)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                             [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                 [0m
[0m[38;5;234m                                                                                                                                              [0m
[38;5;234m• Remote repository URI                                                                                                                       [0m
[38;5;234m• Clone target (absolute path)                                                                                                                [0m
[38;5;234m• Reference (branch, tag...)                                                                                                                  [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                             [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                                   [0m
[0m[38;5;234m                                                                                                                                              [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mTemporarily clone git repository[38;5;234m [0m[38;5;234m                                                                                                           [0m
[0m[38;5;234m  [0m[38;5;235m  tmp = temppath[38;5;234m [0m[38;5;234m                                                                                                                           [0m
[0m[38;5;234m  [0m[38;5;235m  git.clone https://www.example.com/foobar.git <tmp> main[38;5;234m [0m[38;5;234m                                                                                  [0m
[0m
