
[38;5;228;48;5;63;1m git.clone [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                  [0m
[0m[38;5;252m                                                                                                                                              [0m
[38;5;252mClone a git repository (if the repository already exists locally, pull the last commit) and switch to the requested reference (branch, tag...)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                             [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                 [0m
[0m[38;5;252m                                                                                                                                              [0m
[38;5;252m• Remote repository URI                                                                                                                       [0m
[38;5;252m• Clone target (absolute path)                                                                                                                [0m
[38;5;252m• Reference (branch, tag...)                                                                                                                  [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                             [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                   [0m
[0m[38;5;252m                                                                                                                                              [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mTemporarily clone git repository[38;5;252m [0m[38;5;252m                                                                                                           [0m
[0m[38;5;252m  [0m[38;5;251m  tmp = temppath[38;5;252m [0m[38;5;252m                                                                                                                           [0m
[0m[38;5;252m  [0m[38;5;251m  git.clone https://www.example.com/foobar.git <tmp> main[38;5;252m [0m[38;5;252m                                                                                  [0m
[0m
