
[38;5;228;48;5;63;1m git.hash [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                      [0m
[0m[38;5;252m                                                                                 [0m
[38;5;252mGet the latest hash for a reference (generally branch or tag) in a git repository[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                    [0m
[0m[38;5;252m                                                                                 [0m
[38;5;252m• Git repository URI                                                             [0m
[38;5;252m• Reference (generally, branch or tag)                                           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                [0m
[0m[38;5;39;1m## Outputs[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                      [0m
[0m[38;5;252m                                                                                 [0m
[38;5;252m• Commit hash                                                                    [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                      [0m
[0m[38;5;252m                                                                                 [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mPop Shell[38;5;252m [0m[38;5;252m                                                                     [0m
[0m[38;5;252m  [0m[38;5;251m  pophash = git.hash https://github.com/pop-os/shell.git master[38;5;252m [0m[38;5;252m               [0m
[0m
