
[38;5;228;48;5;63;1m github.latest.stable [0m[38;5;234m[38;5;234m [0m[38;5;234m                                          [0m
[0m[38;5;234m                                                                 [0m
[38;5;234mCheck the latest stable release from a GitHub repository         [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                    [0m
[0m[38;5;234m                                                                 [0m
[38;5;234m• GitHub repository name                                         [0m
[38;5;234m• Pattern to match an asset                                      [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                [0m
[0m[38;5;27;1m## Outputs[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                      [0m
[0m[38;5;234m                                                                 [0m
[38;5;234m• Release name                                                   [0m
[38;5;234m• Asset URL                                                      [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                      [0m
[0m[38;5;234m                                                                 [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mKmonad[38;5;234m [0m[38;5;234m                                                        [0m
[0m[38;5;234m  [0m[38;5;235m  release url = github.latest.stable kmonad/kmonad kmonad-*-linux[0m
[0m
