
[38;5;228;48;5;63;1m gnome.extension.install [0m[38;5;252m[38;5;252m [0m[38;5;252m                               [0m
[0m[38;5;252m                                                         [0m
[38;5;252mInstall a GNOME Shell extension from extensions.gnome.org[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                        [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                            [0m
[0m[38;5;252m                                                         [0m
[38;5;252m• Extension UUID                                         [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                        [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                              [0m
[0m[38;5;252m                                                         [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mDash to dock[38;5;252m [0m[38;5;252m                                          [0m
[0m[38;5;252m  [0m[38;5;251m  gnome.extension.install dash-to-dock@micxgx.gmail.com[0m
[0m[38;5;252m  [0m[38;5;251m  gnome.extension.enable dash-to-dock@micxgx.gmail.com[38;5;252m [0m
[0m
