
[38;5;228;48;5;63;1m http.get.var [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                           [0m
[0m[38;5;234m                                                                          [0m
[38;5;234mDownload content with a HTTP GET request (URI is downloaded when checking)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                         [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                             [0m
[0m[38;5;234m                                                                          [0m
[38;5;234m• URI of the content to download                                          [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                         [0m
[0m[38;5;27;1m## Outputs[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                               [0m
[0m[38;5;234m                                                                          [0m
[38;5;234m• Downloaded content                                                      [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                         [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                               [0m
[0m[38;5;234m                                                                          [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mDownload example[38;5;234m [0m[38;5;234m                                                       [0m
[0m[38;5;234m  [0m[38;5;235m  foobar = http.get.var http://www.example.com[38;5;234m [0m[38;5;234m                         [0m
[0m
