
[38;5;228;48;5;63;1m http.get.var [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                           [0m
[0m[38;5;252m                                                                          [0m
[38;5;252mDownload content with a HTTP GET request (URI is downloaded when checking)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                         [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                             [0m
[0m[38;5;252m                                                                          [0m
[38;5;252m• URI of the content to download                                          [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                         [0m
[0m[38;5;39;1m## Outputs[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                               [0m
[0m[38;5;252m                                                                          [0m
[38;5;252m• Downloaded content                                                      [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                         [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                               [0m
[0m[38;5;252m                                                                          [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mDownload example[38;5;252m [0m[38;5;252m                                                       [0m
[0m[38;5;252m  [0m[38;5;251m  foobar = http.get.var http://www.example.com[38;5;252m [0m[38;5;252m                         [0m
[0m
