
[38;5;228;48;5;63;1m nm.import [0m[38;5;252m[38;5;252m [0m[38;5;252m                                [0m
[0m[38;5;252m                                            [0m
[38;5;252mImport a VPN configuration in NetworkManager[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                           [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                               [0m
[0m[38;5;252m                                            [0m
[38;5;252m• Type of the VPN                           [0m
[38;5;252m• Path of the configuration file to import  [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                           [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                 [0m
[0m[38;5;252m                                            [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mImport my VPN configuration[38;5;252m [0m[38;5;252m              [0m
[0m[38;5;252m  [0m[38;5;251m  nm.import openvpn /opt/openvpn.conf[38;5;252m [0m[38;5;252m    [0m
[0m
