
[38;5;228;48;5;63;1m tempdir [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                    [0m
[0m[38;5;234m                                                                                              [0m
[38;5;234mCreate a temporary directory (directory is automatically deleted when closing the application)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                             [0m
[0m[38;5;27;1m## Outputs[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                   [0m
[0m[38;5;234m                                                                                              [0m
[38;5;234m• Path of the created directory                                                               [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                             [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                   [0m
[0m[38;5;234m                                                                                              [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mTemporarily clone git repository[38;5;234m [0m[38;5;234m                                                           [0m
[0m[38;5;234m  [0m[38;5;235m  tmp = tempdir[38;5;234m [0m[38;5;234m                                                                            [0m
[0m[38;5;234m  [0m[38;5;235m  git.clone https://www.example.com/foobar.git <tmp>[38;5;234m [0m[38;5;234m                                       [0m
[0m
