
[38;5;228;48;5;63;1m user.systemd.enable [0m[38;5;252m[38;5;252m [0m[38;5;252m                 [0m
[0m[38;5;252m                                       [0m
[38;5;252mEnable and start a systemd user service[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                      [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                          [0m
[0m[38;5;252m                                       [0m
[38;5;252m• Username                             [0m
[38;5;252m• Name of the service to enable        [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                      [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                            [0m
[0m[38;5;252m                                       [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mEnable syncthing[38;5;252m [0m[38;5;252m                    [0m
[0m[38;5;252m  [0m[38;5;251m  systemd.enable alice syncthing[38;5;252m [0m[38;5;252m    [0m
[0m
