
[38;5;228;48;5;63;1m user.git.clone [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                              [0m
[0m[38;5;252m                                                                                                                                                               [0m
[38;5;252mClone a git repository as provided user (if the repository already exists locally, pull the last commit) and switch to the requested reference (branch, tag...)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                                              [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                                  [0m
[0m[38;5;252m                                                                                                                                                               [0m
[38;5;252m• Username                                                                                                                                                     [0m
[38;5;252m• Remote repository URI                                                                                                                                        [0m
[38;5;252m• Clone target (if path is relative, it is relative to the user's nome directory)                                                                              [0m
[38;5;252m• Reference (branch, tag...)                                                                                                                                   [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                                              [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                                                    [0m
[0m[38;5;252m                                                                                                                                                               [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mOh My Bash[38;5;252m [0m[38;5;252m                                                                                                                                                  [0m
[0m[38;5;252m  [0m[38;5;251m  user.git.clone alice https://github.com/ohmybash/oh-my-bash.git .oh-my-bash master[38;5;252m [0m[38;5;252m                                                                        [0m
[0m
