
[38;5;228;48;5;63;1m user.file.directory [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                          [0m
[0m[38;5;252m                                                                                                                [0m
[38;5;252mCreate a directory belonging to the given user (if path is relative, it is relative to the user's home directory[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                               [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                   [0m
[0m[38;5;252m                                                                                                                [0m
[38;5;252m• Username                                                                                                      [0m
[38;5;252m• Directory path                                                                                                [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                               [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                     [0m
[0m[38;5;252m                                                                                                                [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mCreate Picz photos for alice[38;5;252m [0m[38;5;252m                                                                                 [0m
[0m[38;5;252m  [0m[38;5;251m  user.file.directory alice Picz[38;5;252m [0m[38;5;252m                                                                             [0m
[0m
