
[38;5;228;48;5;63;1m user.file.content [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                            [0m
[0m[38;5;234m                                                                                                [0m
[38;5;234mCreate a file owned by a user (if path is relative, it is relative to the user's home directory)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                               [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                   [0m
[0m[38;5;234m                                                                                                [0m
[38;5;234m• Username                                                                                      [0m
[38;5;234m• Path of the file                                                                              [0m
[38;5;234m• Content of the file                                                                           [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                               [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                     [0m
[0m[38;5;234m                                                                                                [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mSay hello in /home/alice/hello.txt[38;5;234m [0m[38;5;234m                                                           [0m
[0m[38;5;234m  [0m[38;5;235m  user.file.content alice hello.txt "Hello World!"[38;5;234m [0m[38;5;234m                                           [0m
[0m
