
[38;5;228;48;5;63;1m user.file.content [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                            [0m
[0m[38;5;252m                                                                                                [0m
[38;5;252mCreate a file owned by a user (if path is relative, it is relative to the user's home directory)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                               [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                   [0m
[0m[38;5;252m                                                                                                [0m
[38;5;252m• Username                                                                                      [0m
[38;5;252m• Path of the file                                                                              [0m
[38;5;252m• Content of the file                                                                           [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                               [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                     [0m
[0m[38;5;252m                                                                                                [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mSay hello in /home/alice/hello.txt[38;5;252m [0m[38;5;252m                                                           [0m
[0m[38;5;252m  [0m[38;5;251m  user.file.content alice hello.txt "Hello World!"[38;5;252m [0m[38;5;252m                                           [0m
[0m
