
[38;5;228;48;5;63;1m user.vscode.extension.install [0m[38;5;252m[38;5;252m [0m[38;5;252m               [0m
[0m[38;5;252m                                               [0m
[38;5;252mInstall a VSCode extension                     [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                              [0m
[0m[38;5;39;1m## Arguments[0m[38;5;252m[38;5;252m [0m[38;5;252m                                  [0m
[0m[38;5;252m                                               [0m
[38;5;252m• Username                                     [0m
[38;5;252m• Extension identifier                         [0m
[38;5;252m[38;5;252m [0m[38;5;252m                                              [0m
[0m[38;5;39;1m## Example[0m[38;5;252m[38;5;252m [0m[38;5;252m                                    [0m
[0m[38;5;252m                                               [0m
[38;5;251m[0m[38;5;252m  [0m[38;5;251mVSCode with go[38;5;252m [0m[38;5;252m                              [0m
[0m[38;5;252m  [0m[38;5;251m  snap.install code classic[38;5;252m [0m[38;5;252m                 [0m
[0m[38;5;252m  [0m[38;5;251m  user.vscode.extension.install alice[38;5;252m [0m[38;5;252m       [0m
[0m[38;5;251mgolang.go[38;5;252m [0m[38;5;252m                                     [0m
[0m
