
[38;5;228;48;5;63;1m xdg.mimedefault [0m[38;5;234m[38;5;234m [0m[38;5;234m                           [0m
[0m[38;5;234m                                             [0m
[38;5;234mSet the default application for a mimetype   [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                            [0m
[0m[38;5;27;1m## Arguments[0m[38;5;234m[38;5;234m [0m[38;5;234m                                [0m
[0m[38;5;234m                                             [0m
[38;5;234m• Mimetype                                   [0m
[38;5;234m• Name of the application                    [0m
[38;5;234m[38;5;234m [0m[38;5;234m                                            [0m
[0m[38;5;27;1m## Example[0m[38;5;234m[38;5;234m [0m[38;5;234m                                  [0m
[0m[38;5;234m                                             [0m
[38;5;235m[0m[38;5;234m  [0m[38;5;235mUse Chromium[38;5;234m [0m[38;5;234m                              [0m
[0m[38;5;234m  [0m[38;5;235m  xdg.mimedefault text/html[38;5;234m [0m[38;5;234m               [0m
[0m[38;5;235mchromium_chromium[38;5;234m [0m[38;5;234m                           [0m
[0m
