
[38;5;228;48;5;63;1m all ubuntu repo [0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                   [0m
[0m[38;5;252m                                                                                                                     [0m
[38;5;252mConfigure apt sources.list with all sections from an Ubuntu mirror (see [0m[38;5;30;4mhttps://launchpad.net/ubuntu/+archivemirrors[0m[38;5;252m)[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                                    [0m
[0m[38;5;39;1m## Variables[0m[38;5;252m[38;5;252m [0m[38;5;252m                                                                                                        [0m
[0m[38;5;252m                                                                                                                     [0m
[38;5;252m• mirror: URL of the mirror (eg "http://archive.ubuntu.com/ubuntu/")                                                 [0m

