
[38;5;228;48;5;63;1m all ubuntu repo [0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                   [0m
[0m[38;5;234m                                                                                                                     [0m
[38;5;234mConfigure apt sources.list with all sections from an Ubuntu mirror (see [0m[38;5;36;4mhttps://launchpad.net/ubuntu/+archivemirrors[0m[38;5;234m)[0m
[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                                    [0m
[0m[38;5;27;1m## Variables[0m[38;5;234m[38;5;234m [0m[38;5;234m                                                                                                        [0m
[0m[38;5;234m                                                                                                                     [0m
[38;5;234m• mirror: URL of the mirror (eg "http://archive.ubuntu.com/ubuntu/")                                                 [0m

