
[38;5;228;48;5;63;1m apt sources.list [0m[38;5;252m[38;5;252m [0m[38;5;252m                             [0m
[0m[38;5;252m                                                [0m
[38;5;252mChange the sources list file for APT from a file[0m
[38;5;252m[38;5;252m [0m[38;5;252m                                               [0m
[0m[38;5;39;1m## Variables[0m[38;5;252m[38;5;252m [0m[38;5;252m                                   [0m
[0m[38;5;252m                                                [0m
[38;5;252m• src: Path of the file to use as sources.list  [0m

