baseURL: https://tiramiseb.github.io/quickonf/
title: Quickonf
defaultContentLanguage: en
uglyURLs: true

params:
  description: Quickly (re)configure a Linux desktop system
  pages:
    - intro
    - language
    - commands
    - recipes
    - ui

markup:
  highlight:
    noClasses: false
