// Code generated by "embedded-cookbook". DO NOT EDIT.

package instructions

import "github.com/tiramiseb/quickonf/commands"

func init() {
	recipes["apt sources.list"] = []Instruction{
		&Command{
			Command: commands.UGet("file.read"),
			Arguments: []string{
				`<src>`,
			},
			Targets: []string{
				`aptsrc`,
			},
		},
		&Expand{
			Variable: "aptsrc",
		},
		&Command{
			Command: commands.UGet("file.content"),
			Arguments: []string{
				`/etc/apt/sources.list`,
				`<aptsrc>`,
			},
		},
		&Command{
			Command: commands.UGet("apt.upgrade"),
		},
	}
	recipes["no automatic apt updates"] = []Instruction{
		&Command{
			Command: commands.UGet("file.content"),
			Arguments: []string{
				`/etc/apt/apt.conf.d/10periodic`,
				`# Placed by Quickonf
APT::Periodic::Update-Package-Lists 0;
APT::Periodic::Download-Upgradeable-Packages 0;
APT::Periodic::AutocleanInterval 0;
`,
			},
		},
	}
}
